# Generated by Django 2.2.7 on 2019-11-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validated', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmethod',
            name='is_qs_method',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
