# Generated by Django 2.2.7 on 2019-11-18 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validated', '0002_testmethod_is_qs_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmethod',
            old_name='is_qs_method',
            new_name='is_class_method',
        ),
    ]
