# Generated by Django 2.2.7 on 2019-11-18 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('validated', '0003_auto_20191118_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='validated.TestMethod'),
        ),
    ]
